version: 2
updates:
  - package-ecosystem: "pip" # Use pip to manage Python packages
    directory: "/" # Location of your requirements.txt file (root of the repo in this case)
    schedule:
      interval: "daily"
