name: Auto Merge Dependabot PRs
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # Allows manual triggering without inputs

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Dependabot PRs
        id: dependabot_prs
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc'
            });
            const dependabotPRs = prs.data.filter(pr => 
              pr.user.login === 'dependabot[bot]' && 
              pr.title.startsWith('Bump ')
            );
            console.log(`Found ${dependabotPRs.length} open Dependabot PRs`);
            return dependabotPRs;

      - name: Process Dependabot PRs
        if: steps.dependabot_prs.outputs.result != '[]'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prs = JSON.parse('${{ steps.dependabot_prs.outputs.result }}');
            for (const pr of prs) {
              console.log(`Processing PR #${pr.number}: ${pr.title}`);
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: 'APPROVE'
              });
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log(`Merged PR #${pr.number}`);
            }

      - name: No Dependabot PRs found
        if: steps.dependabot_prs.outputs.result == '[]'
        run: echo "No open Dependabot PRs found to merge."
