name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
