name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: startsWith(github.event.pull_request.title, 'Bump')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-merge PR
        uses: ahmadnassri/action-merge-me@v1.6.0  # Updated and maintained action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
