# File: .github/workflows/auto_merge_dependabot.yml

name: Auto Merge Dependabot PRs

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run Dependabot PR merge script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/merge_dependabot_prs.py
