name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on pull request events
  workflow_dispatch:  # Also allow manual triggering

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: startsWith(github.event.pull_request.title, 'Bump')  # Dependabot PRs start with 'Bump'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
